---
snowflake:
  credentials:
    # account & user: mandatory related to the Snowflake account.
    account: xxxxxx.west-europe.azure
    user: xxxxxx

    # password: needed for a connection with Snowflake credentials.
    password: xxxxxx

    # authenticator: needed for a connection through SSO.
    # authenticator: externalbrowser

    role: ACCOUNTADMIN

settings:
  run_dry: true
  new_owner: SYSADMIN
  databases:
    - DEV
