---
snowflake:
  credentials:
    # account & user: mandatory related to the Snowflake account.
    account: xxxxxx.west-europe.azure
    user: xxxxxx

    # password: needed for a connection with Snowflake credentials.
    password: xxxxxx

    # authenticator: needed for a connection through SSO.
    # authenticator: externalbrowser

settings:
  run_dry: true
  new_owner: ACCOUNTADMIN
  databases:
    - DEV_TLS
    - DEV_LND
    - DEV_BRZ
    - DEV_SLV
    - DEV_GLD
    - TST_TLS
    - TST_LND
    - TST_BRZ
    - TST_SLV
    - TST_GLD
    - PRD_TLS
    - PRD_LND
    - PRD_BRZ
    - PRD_SLV
    - PRD_GLD
