name: Quality Code Review

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.11

      - name: Install dependencies with pipenv
        run: |
          pip install pipenv
          pipenv install --deploy --dev

      - run: pipenv run yamllint ./snowflake_reset
      - run: pipenv run pyright ./snowflake_reset
      - run: pipenv run pylint ./snowflake_reset
      - run: pipenv run flake8 ./snowflake_reset
      - run: pipenv run mypy ./snowflake_reset
      - run: pipenv run pylama ./snowflake_reset
      - run: pipenv run yapf ./snowflake_reset --recursive
